// <auto-generated />
namespace Virtual_ATM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_ref_to_account : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_ref_to_account));
        
        string IMigrationMetadata.Id
        {
            get { return "201505212353460_added_ref_to_account"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
